org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
skipDependencyChecks=true
android.builder.sdkDownload=false
android.suppressUnsupportedCompileSdk=36
android.suppressUnsupportedCompileSdk=35
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false

